name: ci
on:
  push:
    branches: 
    - master
    tags:
    - v*
  pull_request: 
jobs:
  test:
    runs-on: ubuntu-latest
    name: Go ${{ matrix.go }} test
    strategy:
      matrix:
        go: ["1.16", "1.17", "1.18"]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}
      - run: go test -v ./...
